###
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  . /etc/bash_completion
fi

###
# Enable MacPorts bash completion, if applicable.
if [ -f /opt/local/etc/bash_completion ]; then
    . /opt/local/etc/bash_completion
fi
if [ -f /opt/local/share/spotify-cli/spotify-cli ]; then
    . /opt/local/share/spotify-cli/spotify-cli
fi

. $HOME/.bash/exports.sh
. $HOME/.bash/aliases.sh
. $HOME/.bash/functions.sh

which opam > /dev/null && eval `opam config env`
