if has('vim_starting')
    set nocompatible

    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

NeoBundle 'scrooloose/nerdcommenter'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tmhedberg/matchit'
NeoBundle 'sbl/scvim'

" Filetype detection.
au BufRead,BufNewFile *xensource.log* set filetype=messages

" General editor settings.
syntax on
filetype plugin indent on

" Filetype-specific settings.
au FileType c setl sw=4 sts=4 ts=4 expandtab
au FileType cmake setl sw=4 sts=4 ts=4 expandtab
au FileType cpp setl sw=4 sts=4 ts=4 expandtab
au FileType css setl sw=4 sts=4 ts=4 expandtab
au FileType cucumber setl sw=4 sts=4 ts=4 expandtab
au FileType erlang setl sw=4 sts=4 ts=4 expandtab
au FileType haskell setl sw=4 sts=4 ts=4 expandtab
au FileType html setl sw=4 sts=4 ts=4 expandtab
au FileType javascript setl sw=4 sts=4 ts=4 tw=0 wrapmargin=0 expandtab
au FileType ocaml setl sw=2 sts=2 ts=2 tw=0 wrapmargin=0 expandtab
au FileType python setl sw=4 sts=4 ts=4 expandtab
au FileType ruby setl sw=4 sts=4 ts=4 expandtab
au FileType sh setl sw=4 sts=4 ts=4 expandtab
au FileType vim setl sw=4 sts=4 ts=4 expandtab
au FileType yaml setl sw=4 sts=4 ts=4 expandtab

" Visual settings.
colorscheme desert

set statusline=%t%m%r%h%w\ \ \ [BUF=%02n]\ \ \ [TYPE=%Y]\ \ \ [POS=%03l,%03c(%03v)][%03p%%]\ \ \ [LEN=%L]
set laststatus=2

if exists("&colorcolumn")
    set colorcolumn=81
endif

set cursorline
set hls
set list
set listchars=tab:.─,trail:∘,eol:$
"set listchars=tab:┼─,trail:∘

" Search.
set incsearch

" Tab completion.
set wildmode=longest:full
set wildmenu

" Turn off ex mode command, replace with simpler access to the q macro.
map Q @q

" Edit .vimrc easily.
nnoremap <leader>ev :vsplit $MYVIMRC<cr>

" NERDTree bits.
nnoremap <C-l> :NERDTreeFind<CR>
nnoremap <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\.swp$', '\.a$', '\.cmxa$', '\.o$', '\.spit$', '\.spot$', '\.cmi$', '\.cmx$', '\.annot$']

" Enable Merlin
let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"

let g:syntastic_ocaml_checkers = ['merlin']
