" Filetype detection.
au BufRead,BufNewFile *xensource.log* set filetype=messages

" General editor settings.
syntax on
filetype plugin indent on

" Filetype-specific settings.
au FileType ocaml setl sw=2 sts=2 ts=2 tw=0 wrapmargin=0 noexpandtab
au FileType javascript setl sw=4 sts=4 ts=4 tw=0 wrapmargin=0 expandtab
au FileType python setl sw=4 sts=4 ts=4 expandtab
au FileType ruby setl sw=4 sts=4 ts=4 expandtab
au FileType sh setl sw=4 sts=4 ts=4 expandtab
au FileType css setl sw=4 sts=4 ts=4 expandtab
au FileType html setl sw=4 sts=4 ts=4 expandtab
au FileType vim setl sw=4 sts=4 ts=4 expandtab
au FileType c setl sw=4 sts=4 ts=4 expandtab
au FileType erlang setl sw=4 sts=4 ts=4 expandtab
au FileType haskell setl sw=4 sts=4 ts=4 expandtab

" Visual settings.
colorscheme desert

set statusline=%t%m%r%h%w\ \ \ [BUF=%02n]\ \ \ [TYPE=%Y]\ \ \ [POS=%03l,%03c(%03v)][%03p%%]\ \ \ [LEN=%L]
set laststatus=2

if exists("&colorcolumn")
    set colorcolumn=80
endif

set cursorline
set hls
set list
set listchars=tab:.─,trail:∘,eol:$
"set listchars=tab:┼─,trail:∘

" Search.
set incsearch

" Tab completion.
set wildmode=longest:full
set wildmenu

" Turn off ex mode command, replace with simpler access to the q macro.
map Q @q

" Edit .vimrc easily.
nnoremap <leader>ev :vsplit $MYVIMRC<cr>

" NERDTree bits.
nnoremap <C-l> :NERDTreeFind<CR>
nnoremap <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\.swp$', '\.a$', '\.cmxa$', '\.o$', '\.spit$', '\.spot$', '\.cmi$', '\.cmx$', '\.annot$']

" Enable Merlin
let s:ocamlmerlin=substitute(system('opam config var share'),'\n$','','''') .  "/ocamlmerlin"
execute "set rtp+=".s:ocamlmerlin."/vim"
execute "set rtp+=".s:ocamlmerlin."/vimbufsync"

let g:syntastic_ocaml_checkers = ['merlin']
