#!/bin/bash

# Script to create an index.html containing links to each file in a directory.

IFS=$(echo -en "\n\b")

FORCE=false

while getopts ":f" opt
do
    case $opt in
        f)
            FORCE=true
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
    esac
done

if [ -a index.html -a $FORCE == false ]
then
    echo "index.html already exists - use -f to force"
    exit 1
fi

for ITEM in `ls`
do
    echo "<p><a href=\"$ITEM\">$ITEM</a></p>" >> index.html
done
