#!/bin/bash

# Script to create an index.html containing links to each file in a directory.

IFS=$(echo -en "\n\b")

if [ -a index.html ]
then
    echo "index.html already exists"
    exit 1
fi

for ITEM in `ls --color=none`
do
    echo "<p><a href=\"$ITEM\">$ITEM</a></p>" >> index.html
done
