#!/bin/bash

FILEPATH=$1
[ -z "$FILEPATH" ]   && echo "error: \$FILEPATH is empty" && return 1
[ -e "$FILEPATH.h" ] && echo "error: \$FILEPATH.h exists" && return 1

FILENAME=$(basename $1)
YEAR=$(date +%Y)

cat << EOF > "${FILEPATH}.h"
//==============================================================================
// ${FILENAME}.h
// Copyright ${YEAR} inMusic Brands. All rights reserved.
//==============================================================================

#pragma once
EOF
