#!/bin/bash

set -eux

if [[ $# -ne 1 ]]
then
    echo "usage: $0 <script-name>"
    exit 1
fi

SCRIPT_NAME=$1.py

cat <<EOF > $SCRIPT_NAME
#!/usr/bin/env python3

def main():
    pass

if __name__ == "__main__":
    main()
EOF

chmod 755 $SCRIPT_NAME
