#!/bin/bash

ICON=/usr/share/icons/hicolor/64x64/apps/spotify-client.png

function notify() {
    eval `spotify-cli now-playing`
    notify-send -i $ICON \
        "$spotify_artist_name" \
        "$spotify_track_name"
}

function next() {
    spotify-cli next
}

function play-pause() {
    spotify-cli play-pause
}

function previous() {
    spotify-cli previous
}

case "$1" in
    notify)
        notify
        ;;
    next)
        next
        sleep 0.1
        notify
        ;;
    play-pause)
        play-pause
        ;;
    previous)
        previous
        sleep 0.1
        notify
        ;;
    *)
        echo "unknown command: $1"
        exit 1
esac
