#!/bin/bash

ICON=/usr/share/icons/hicolor/64x64/apps/spotify-client.png

function notify() {
    NOW_PLAYING=`spotify-cli now-playing`
    notify-send -i $ICON "${NOW_PLAYING}"
}

function next() {
    spotify-cli next
}

function play-pause() {
    spotify-cli play-pause
}

function previous() {
    spotify-cli previous
}

case "$1" in
    notify)
        notify
        ;;
    next)
        next
        notify
        ;;
    play-pause)
        play-pause
        ;;
    previous)
        previous
        notify
        ;;
    *)
        echo "unknown command: $1"
        exit 1
esac
