#!/bin/bash

function start_buildroot_session() {
    CODE_ROOT="$1"
    CODE_DIR="$2"

    SESSION_NAME="AZ01-${CODE_DIR//\./_}"

    tmux new-session -d -s "$SESSION_NAME" -n 'AZ01'

    tmux new-window -t "$SESSION_NAME":1 -n 'AZ01'
    tmux new-window -t "$SESSION_NAME":2 -n 'ACVS'
    tmux new-window -t "$SESSION_NAME":3 -n 'ACVS'

    tmux send-keys -t "$SESSION_NAME":0 "cd $CODE_ROOT/$CODE_DIR/AZ01" C-m
    tmux send-keys -t "$SESSION_NAME":1 "cd $CODE_ROOT/$CODE_DIR/AZ01" C-m
    tmux send-keys -t "$SESSION_NAME":2 "cd $CODE_ROOT/$CODE_DIR/ACVS/Software/Source" C-m
    tmux send-keys -t "$SESSION_NAME":3 "cd $CODE_ROOT/$CODE_DIR/ACVS/Software/Source" C-m
}

function start_yocto_session() {
    CODE_ROOT="$1"
    CODE_DIR="$2"

    SESSION_NAME="yocto-${CODE_DIR//\./_}"

    tmux new-session -d -s "$SESSION_NAME" -n 'yocto'
    tmux send-keys -t "$SESSION_NAME":0 "cd $CODE_ROOT/$CODE_DIR" C-m
    tmux split-window -h -t "$SESSION_NAME":0
    tmux send-keys -t "$SESSION_NAME":0 "cd $CODE_ROOT/$CODE_DIR" C-m
    tmux send-keys -t "$SESSION_NAME":0 ". poky/oe-init-build-env build" C-m

    tmux new-window -t "$SESSION_NAME":1 -n 'ACVS'
    tmux new-window -t "$SESSION_NAME":2 -n 'ACVS'

    tmux send-keys -t "$SESSION_NAME":1 "cd $CODE_ROOT/$CODE_DIR/ACVS/Software/Source" C-m
    tmux send-keys -t "$SESSION_NAME":2 "cd $CODE_ROOT/$CODE_DIR/ACVS/Software/Source" C-m
}

cd ~
tmux start-server

case `uname -s` in
    Darwin)
        # ACVS-mpc2
        tmux new-session -d -s ACVS-mpc2 -n 'todo'

        tmux new-window -t ACVS-mpc2:1 -n 'builds'
        tmux new-window -t ACVS-mpc2:2 -n 'ACVS'
        tmux new-window -t ACVS-mpc2:3 -n 'ACVS'

        tmux send-keys -t ACVS-mpc2:0 'vim Sync/default/work/notes/inMusic/cheatsheet.txt Sync/default/work/notes/inMusic/todo*' C-m
        tmux send-keys -t ACVS-mpc2:1 'cd Code/inMusic/builds/mpc2' C-m
        tmux send-keys -t ACVS-mpc2:2 'cd Code/inMusic/ACVS-mpc2/Software/Source' C-m
        tmux send-keys -t ACVS-mpc2:3 'cd Code/inMusic/ACVS-mpc2/Software/Source' C-m

        # ACVS-main
        tmux new-session -d -s ACVS-main -n 'builds'

        tmux new-window -t ACVS-main:1 -n 'ACVS'
        tmux new-window -t ACVS-main:2 -n 'ACVS'

        tmux send-keys -t ACVS-main:0 'cd Code/inMusic/builds/main'               C-m
        tmux send-keys -t ACVS-main:1 'cd Code/inMusic/ACVS-main/Software/Source' C-m
        tmux send-keys -t ACVS-main:2 'cd Code/inMusic/ACVS-main/Software/Source' C-m

        # ACVS-release
        tmux new-session -d -s ACVS-release

        tmux new-window -t ACVS-release:1 -n 'ACVS'
        tmux new-window -t ACVS-release:2 -n 'ACVS'

        tmux send-keys -t ACVS-release:0 'cd Code/inMusic/builds/release' C-m
        tmux send-keys -t ACVS-release:1 'cd Code/inMusic/ACVS-release/Software/Source' C-m
        tmux send-keys -t ACVS-release:2 'cd Code/inMusic/ACVS-release/Software/Source' C-m

        # ACVS-tests
        tmux new-session -d -s ACVS-tests

        tmux new-window -t ACVS-tests:1

        tmux send-keys -t ACVS-tests:0 'cd Code/inmusic/ACVS-tests' C-m
        tmux send-keys -t ACVS-tests:1 'cd Code/inmusic/ACVS-tests' C-m

        # az01
        tmux new-session -d -s az01

        tmux new-window -t az01:1
        tmux new-window -t az01:2
        tmux new-window -t az01:3

        tmux send-keys -t az01:0 'cd az01/builds' C-m
        tmux send-keys -t az01:1 'cd az01/updater-assets-sme0' C-m
        tmux send-keys -t az01:2 'cd az01/updater-assets-sme1' C-m
        tmux send-keys -t az01:3 'cd az01/updater-assets-sme5' C-m

        tmux select-window -t ACVS-mpc2:0
        tmux -2 attach-session -t ACVS-mpc2
        ;;
    Linux)
        case `hostname` in
            dylan)
                CODE_ROOT="/media/john/transcend1/Code/inmusic"
                ;;
            ermintrude)
                CODE_ROOT="/volumes/data1/Code/inMusic"
                ;;
        esac

        if [ ! -d "$CODE_ROOT" ]
        then
            echo "Drive not attached"
            exit 1
        fi

        start_buildroot_session "$CODE_ROOT" sme0-staging-mpc2
        start_buildroot_session "$CODE_ROOT" 2.x
        start_buildroot_session "$CODE_ROOT" 3.x

        start_yocto_session "$CODE_ROOT" sme0-main
        start_yocto_session "$CODE_ROOT" sme1-main
        start_yocto_session "$CODE_ROOT" sme5-main
        start_yocto_session "$CODE_ROOT" sme5-mpc3-factory

        # desktop
        tmux new-session -d -s desktop -n "builds"
        tmux send-keys -t desktop:0 "cd $CODE_ROOT/builds/main" C-m

        tmux select-window -t yocto-sme0-main:0
        tmux -2 attach-session -t yocto-sme0-main
        ;;
esac
